# Generated by Django 3.2.2 on 2021-05-09 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCategories',
            new_name='ItemCategory',
        ),
        migrations.RenameModel(
            old_name='ItemImages',
            new_name='ItemImage',
        ),
    ]
