# Generated by Django 3.2.2 on 2021-05-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0002_auto_20210509_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
