# Generated by Django 3.2.2 on 2021-06-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0002_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
