# Generated by Django 3.2.2 on 2021-06-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendormgmt', '0001_initial'),
        ('itemmgmt', '0003_itemimage_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cost_price', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmgmt.item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormgmt.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
