# Generated by Django 3.2.2 on 2021-05-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0003_alter_item_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
