# Generated by Django 3.2.2 on 2021-06-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0005_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, default='to_be_updated', max_length=100, null=True),
        ),
    ]
