# Generated by Django 3.2.2 on 2021-05-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendormgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
