# Generated by Django 3.2.2 on 2021-05-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendormgmt', '0003_auto_20210509_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='owner_phone',
            field=models.IntegerField(null=True),
        ),
    ]
